apiVersion: batch/v1
kind: Job
metadata:
  name: client
  labels:
    name: client
    app: client
spec:
  template:
    spec:
      containers:
      - name: d1-client
        image: lukaisailovic/d1_client:1
        env: 
          - name: SERVER_URL
            value: http://localhost:8081/users
      restartPolicy: Never
  backoffLimit: 4